# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
---
archives:
  -
    replacements:
      linux: Linux
before:
  hooks:
    - "go mod download"
    - "go generate ./..."
builds:
  -
    env:
      - CGO_ENABLED=0
      - BUILDER=GoReleaser
    goos:
      - linux

dockers:
  - image_templates: ["ghcr.io/doniacld/tiny-hen:{{ .Version }}"]
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/doniacld/tiny-hen
      - --label=org.opencontainers.image.source=https://github.com/doniacld/tiny-hen
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^deploy:"
  sort: asc
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
project_name: tiny-hen
